"""empty message

Revision ID: c1e678f1a7d4
Revises: 
Create Date: 2020-12-30 13:56:51.846660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e678f1a7d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('GSE_num', sa.String(length=20), nullable=True, comment='GSE号'),
    sa.Column('Status', sa.String(length=50), nullable=True, comment='发表时间'),
    sa.Column('Title', sa.String(length=300), nullable=True, comment='标题'),
    sa.Column('Organism', sa.String(length=100), nullable=True, comment='种属'),
    sa.Column('Experiment_type', sa.String(length=100), nullable=True, comment='实验类型'),
    sa.Column('Summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('Overall_design', sa.Text(), nullable=True, comment='实验设计'),
    sa.Column('Platforms', sa.Text(), nullable=True, comment='平台'),
    sa.Column('Samples', sa.Text(), nullable=True, comment='GSM'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gsm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('GSM_num', sa.String(length=20), nullable=True, comment='GSM号'),
    sa.Column('Status', sa.String(length=50), nullable=True, comment='发表时间'),
    sa.Column('Source_name', sa.String(length=200), nullable=True, comment='器官类型'),
    sa.Column('Organism', sa.String(length=100), nullable=True, comment='种属'),
    sa.Column('Characteristics', sa.String(length=1000), nullable=True, comment='实验特征'),
    sa.Column('Extracted_molecule', sa.String(length=100), nullable=True, comment='提取来源'),
    sa.Column('Platform', sa.String(length=300), nullable=True, comment='平台'),
    sa.Column('GSE_num', sa.String(length=20), nullable=True, comment='GSE号'),
    sa.Column('Experiment_type', sa.String(length=100), nullable=True, comment='实验类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='标题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('authors', sa.String(length=1000), nullable=True, comment='作者'),
    sa.Column('pmid', sa.Integer(), nullable=True, comment='PMID'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('gsm')
    op.drop_table('gse')
    # ### end Alembic commands ###
